name: OpenAI on Custom Dataset
on:
  workflow_dispatch:
    inputs:
      resourceGroup:
        description: 'Resource group to deploy'
        required: true
      azureml_workspace:
        description: 'Name of Azure ML workspace'
        required: true
      azsearch_name:
        description: 'Azure Cogntive Search Service Name'
        required: true
      azsearch_index:
        description: 'Azure Cogntive Search Service Name'
        required: true
        default: 'maya_index'
      azsearch_search_key:
        description: 'Azure Cogntive Search Service Name'
        required: false
      region:
        description: 'region of the services'
        required: true
        default: 'westus'
      storageaccount_name:
        description: 'Name of storage account'
        required: True
      azureml_moe_name:
        description: 'name of managed online endpoint in azureml to deploy search ranking service'
        required: True
      azureml_mod_name:
        description: 'name of managed online deployment in azureml to deploy search ranking service'
        required: True
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep files
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        parameters: 'dataFactoryName=${{ github.event.inputs.dataFactoryName }} storageSKU=${{ github.event.inputs.storageSKU }} storageAccountName=${{ github.event.inputs.storageAccountName }} deployStorage=${{ github.event.inputs.deployStorage }} deployADF=${{ github.event.inputs.deployADF }} projectName=${{ github.event.inputs.projectName }} deployprojectName=${{ github.event.inputs.deployprojectName }}'
        template: infrastructure/main.bicep
        failOnStdErr: false
        
